name: Python Actions Collection

on: push

jobs:
  bot-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Set Git user name and email
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"

      - name: Create branch
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const ref = 'refs/heads/target-branch'
            const { sha } = context
            const { repo, owner } = context.repo;
            const result = await github.rest.git.createRef({
              owner,
              repo,
              ref,
              sha,
            });
            console.log(result)

      - name: Create sample txt
        shell: bash
        run: |
          echo "Yellow world!" > report.txt

      - uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            await exec.exec('git', ['add', '.'])
            let diffOutput = '';
            await exec.exec('git', ['commit', '-am', 'test commit.'], {
              listeners: {
                stdout: (data) => {
                  diffOutput += data.toString();
                }
              }
            })
            console.log(diffOutput)
            await exec.exec('git', ['push', 'origin', 'main:target-branch'])

      - name: Get diff using GitHub API
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const compare = await github.rest.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: 'main',
              head: 'target-branch'
            });
      
            console.log(compare.data.files);
#      - uses: actions/github-script@v7
#        with:
#          result-encoding: string
#          script: |
#            let diffOutput = '';
#            await exec.exec('git', ['diff', 'main...origin/target-branch'], {
#              listeners: {
#                stdout: (data) => {
#                  diffOutput += data.toString();
#                }
#              }
#            })
#            console.log(diffOutput)

      - uses: actions/github-script@v7
        with:
          result-encoding: string
          retries: 3
          retry-exempt-status-codes: 400,401
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: '[Example] Simple demo',
              owner,
              repo,
              head: 'target-branch',
              base: 'main',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });